version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: localchat-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: localchat
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - localchat-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: localchat-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - localchat-network
    depends_on:
      - mysql

networks:
  localchat-network:
    driver: bridge
